### ISSUE TITLE
Backup modules

### ISSUE THREAD

**Issue by iskandervito** [davmont/DotProject#1]
Dear
In the module file /modules/backup/do_backup.php the drop functionality does not work which is normal since you initialize a variable $droptable which is never used, instead, the used variable in the code is $drop_table

Please correct this issue
Thanks

**Comment by davmont** [comment]
HI,

This has been solved.

Sorry, but there's a lot of code that has not been reviewed since I added new modules from other repos.

However, please let me know if you find errors, I'll try to start again coding for this project, as I have left it alone for a lot of time.

Thanks for your feedback!
